#@data/values
---
resources:
#  - name: every-morning
#    type: time
#    source:
#      start: 9:00 AM
#      stop: 10:00 AM
#      location: America/Denver
  - name: wavefront-operator-ci
    type: git
    source:
      uri: git@github.com:wavefrontHQ/wavefront-operator-for-kubernetes.git
      branch: corn/gitops # main
      private_key: ((osspi.jcornish-github-private-key)) #! TODO use a deploy key
jobs:
  - name: update-self
    plan:
#      - get: every-morning
#        trigger: true
      - get: wavefront-operator-ci
      - task: try-some-git-stuff
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
          inputs:
          - name: wavefront-operator-ci
          outputs:
          - name: wavefront-operator-ci-with-branch-list
          run:
            path: sh
            args:
            - -cx
            - |
              cd wavefront-operator-ci
              git ls-remote --heads
              git ls-remote --heads \
                | grep -E 'refs/heads/K8SSAAS' \
                | grep -oE 'K8SSAAS-\d{3,4}.*$'
      #! - task: generate-pipeline
      #!   file: wavefront-operator-ci/hack/concourse/tasks/generate-pipeline.yaml
      #!   input_mapping:
      #!     ci_repo: wavefront-operator-ci

      #! generate pipeline based on active branches
      #! trigger 9am or manually
      #! - set_pipeline: operator-gitops
      #!   file: wavefront-operator/hack/concourse/pipeline.yaml

  #!- name: setup-<feature JIRA>-cluster
    #! trigger 9am
    #! trigger on push to branch
    #! for each branch with push today, create dev cluster
    #! I think only trigger on push, but could also be daily
  #!- name: teardown-all-feature-clusters
    #! trigger 5pm
    #! ideal: gcloud search by pattern 'k8po-operator-gitops-<feature JIRA>'
    #! but that's maybe not safe so instead
  #!- name: teardown-<feature JIRA>-cluster

  #!- name: submit-<feature JIRA>-for-acceptance
  #!  plan:
  #!    - get: wavefront-operator
  #!      branch: <feature JIRA>
    #! create acceptance GKE cluster
    #! teardown-<feature JIRA>-cluster
  #!- name: accept-<feature JIRA>
    #! create PR from feature JIRA into release-elect and try to automatically merge
    #! promote release-elect to release
  #!- name: reject-<feature JIRA>
    #! stretch goal: send slack notification or something
