#@data/values
---
resources:
#!  - name: every-morning
#!    type: time
#!    source:
#!      start: 9:00 AM
#!      stop: 10:00 AM
#!      location: America/Denver
#!  - name: every-evening
#!    type: time
#!    source:
#!      start: 5:00 PM
#!      stop: 6:00 PM
#!      location: America/Denver
  - name: wavefront-operator-ci
    type: git
    source:
      uri: git@github.com:wavefrontHQ/wavefront-operator-for-kubernetes.git
      branch: corn/gitops #! main
      private_key: ((osspi.jcornish-github-private-key)) #! TODO use a deploy key
jobs:
  - name: update-self
    plan:
      - get: wavefront-operator-ci
      - task: get-feature-branches
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
          inputs:
          - name: wavefront-operator-ci
          outputs:
          - name: feature-branches
          run:
            path: sh
            args:
            - -cx
            - |
              mkdir -p ~/.ssh
              echo "((osspi.jcornish-github-private-key))" > ~/.ssh/id_ed25519
              echo "((osspi.github-known-host))" > ~/.ssh/known_hosts
              chmod 400 ~/.ssh/id_ed25519
              
              apt update
              apt install -y git
              cd wavefront-operator-ci
              git ls-remote --heads \
                | grep -o 'K8SSAAS-.*$' \
                > ../feature-branches/list.txt
      - task: generate-pipeline
        file: wavefront-operator-ci/hack/concourse/tasks/generate-pipeline.yaml
        input_mapping:
          ci_repo: wavefront-operator-ci
          feature_branches: feature-branches
      - set_pipeline: operator-gitops
        file: generated-pipeline/pipeline.yaml

  #!- name: setup-<feature JIRA>-cluster
    #! trigger 9am
    #! trigger on push to branch
    #! for each branch with push today, create dev cluster
    #! I think only trigger on push, but could also be daily
  #!- name: teardown-all-feature-clusters
    #! trigger 5pm
    #! ideal: gcloud search by pattern 'k8po-operator-gitops-<feature JIRA>'
    #! but that's maybe not safe so instead
  #!- name: teardown-<feature JIRA>-cluster

  #!- name: submit-<feature JIRA>-for-acceptance
  #!  plan:
  #!    - get: wavefront-operator
  #!      branch: <feature JIRA>
    #! create acceptance GKE cluster
    #! teardown-<feature JIRA>-cluster
  #!- name: accept-<feature JIRA>
    #! create PR from feature JIRA into release-elect and try to automatically merge
    #! promote release-elect to release
  #!- name: reject-<feature JIRA>
    #! stretch goal: send slack notification or something
