# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    # reasoning: use exclude rules for things we will not upgrade in a timely manner
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "sigs.k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
