# Need to change YOUR_CLUSTER_NAME and YOUR_WAVEFRONT_URL accordingly
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: wavefront
spec:
  clusterName: YOUR_CLUSTER_NAME
  wavefrontUrl: YOUR_WAVEFRONT_URL
  wavefrontTokenSecret: wavefront-secret
  dataCollection:
    metrics:
      enable: true
  dataExport:
    wavefrontProxy:
      enable: true
      metricPort: 2878
      preprocessor: advanced-proxy-preprocessor-rules
      resources:
        requests:
          cpu: 1500m
          memory: 2Gi
        limits:
          cpu: 2500m
          memory: 4Gi
      replicas: 2
      tracing:
        wavefront:
          port: 30000
          samplingRate: "0.1"
          samplingDuration: 100
        zipkin:
          port: 9411
          applicationName: "zipkin"
        jaeger:
          port: 30001
          httpPort: 30080
          grpcPort: 14250
          applicationName: "jaeger"
      histogram:
        port: 40000
        minutePort: 40001
        hourPort: 40002
        dayPort: 40003
#      httpProxy:
#        secret: http-proxy-secret
      args: |
        --customSourceTags mySource
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: advanced-proxy-preprocessor-rules
  namespace: wavefront
data:
  rules.yaml: |
    '2878':
      - rule: tag-all-metrics-processed
        action: addTag
        tag: processed
        value: "true"

