# Need to change YOUR_CLUSTER_NAME and YOUR_WAVEFRONT_URL accordingly
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: wavefront
spec:
  collectorEnabled: true
  clusterName: YOUR_CLUSTER_NAME
  dataExport:
    proxy:
      metricPort: 2878
      wavefrontUrl: YOUR_WAVEFRONT_URL
      wavefrontTokenSecret: wavefront-secret
      tracing:
        wavefront:
          port: 30000
          samplingRate: 0.1
          samplingDuration: 100

