apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: collector
  name: wavefront-node-collector
  namespace: observability-system
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: wavefront-controller-manager
      uid: {{ .ControllerManagerUID }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name : wavefront
      app.kubernetes.io/component: collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name : wavefront
        app.kubernetes.io/component: collector
      annotations:
        installation-method: operator
        proxy-available-replicas: "{{ .DataExport.WavefrontProxy.AvailableReplicas }}"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      tolerations:
        - effect: NoSchedule
          key: node.alpha.kubernetes.io/role
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      serviceAccountName: wavefront-collector
      containers:
        - name: wavefront-collector
          securityContext:
            readOnlyRootFilesystem: true
          image: projects.registry.vmware.com/tanzu_observability/kubernetes-collector:1.12.0
          imagePullPolicy: Always
          command:
            - /wavefront-collector
            - --agent=node
            - --config-file=/etc/collector/config.yaml
          env:
            - name: HOST_PROC
              value: /host/proc
            - name: POD_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INSTALLATION_METHOD
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations['installation-method']
          ports:
            - containerPort: 8088
              protocol: TCP
          resources:
{{ .DataCollection.Metrics.NodeCollector.Resources | toYaml | indent 12 }}
          volumeMounts:
            - name: procfs
              mountPath: /host/proc
              readOnly: true
            - name: config
              mountPath: /etc/collector/
              readOnly: true
      volumes:
        - name: procfs
          hostPath:
            path: /proc
        - name: config
          configMap:
            name: {{ .DataCollection.Metrics.CollectorConfigName }}