apiVersion: apps/v1
kind: Deployment
metadata:
  name: wavefront-cluster-collector
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: cluster-collector
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: wavefront-controller-manager
      uid: {{ .ControllerManagerUID }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name : wavefront
      app.kubernetes.io/component: cluster-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name : wavefront
        app.kubernetes.io/component: cluster-collector
      annotations:
        installation-method: operator
        proxy-available-replicas: "{{ .DataExport.WavefrontProxy.AvailableReplicas }}"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          value: arm64
      serviceAccountName: wavefront-collector
      automountServiceAccountToken: true
      containers:
        - name: wavefront-cluster-collector
          securityContext:
            readOnlyRootFilesystem: true
          image: {{ .ImageRegistry }}/kubernetes-collector:1.14.0
          imagePullPolicy: Always
          command:
            - /wavefront-collector
            - --agent=cluster
            - --config-file=/etc/collector/config.yaml
          env:
            - name: HOST_PROC
              value: /host/proc
            - name: POD_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INSTALLATION_METHOD
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations['installation-method']
          ports:
            - containerPort: 8088
              protocol: TCP
          resources:
{{ .DataCollection.Metrics.ClusterCollector.Resources | toYaml | indent 12 }}
          volumeMounts:
            - name: procfs
              mountPath: /host/proc
              readOnly: true
            - name: config
              mountPath: /etc/collector/
              readOnly: true
      volumes:
        - name: procfs
          hostPath:
            path: /proc
        - name: config
          configMap:
            name: {{ .DataCollection.Metrics.CollectorConfigName }}