FROM bitnami/fluentd:1.15.2

RUN fluent-gem install 'fluent-plugin-multi-format-parser'
RUN fluent-gem install 'fluent-plugin-concat'
RUN fluent-gem install 'fluent-plugin-record-modifier'
RUN fluent-gem install 'fluent-plugin-kubernetes_metadata_filter'

USER root:root