apiVersion: v1
kind: ServiceAccount
metadata:
  name: wavefront-configurator
  namespace: observability-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-wavefront-cr
  namespace: observability-system
rules:
  - apiGroups:
      - wavefront.com
    resources:
      - wavefronts
    verbs:
      - get
      - update
      - create
      - list
      - watch
      - delete
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-wavefront-cr-to-sa
  namespace: observability-system
subjects:
  - kind: ServiceAccount
    name: wavefront-configurator
    namespace: observability-system
roleRef:
  kind: Role
  name: get-wavefront-cr
  apiGroup: rbac.authorization.k8s.io
