apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-wavefront-cr
  namespace: observability-system
rules:
  - apiGroups:
      - ""
    resources:
      - wavefronts
    verbs:
      - get
      - patch
      - update
