kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wavefront-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wavefront-collector
subjects:
- kind: ServiceAccount
  name: wavefront-collector
  namespace: wavefront
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wavefront-collector
  namespace: wavefront
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wavefront-collector
subjects:
  - kind: ServiceAccount
    name: wavefront-collector
    namespace: wavefront
