resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- components/collector/1-collector-roles.yaml
- components/collector/2-collector-rbac.yaml
- components/logging/1-logging-roles.yaml
- components/logging/2-logging-rbac.yaml
- legacy-installation-detection/1-legacy-install-detection-roles.yaml
- legacy-installation-detection/2-legacy-install-detection-rbac.yaml