# permissions for end users to edit wavefronts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wavefront-editor-role
rules:
- apiGroups:
  - wavefront.com
  resources:
  - wavefronts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wavefront.com
  resources:
  - wavefronts/status
  verbs:
  - get
