# permissions for end users to view wavefronts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wavefront-viewer-role
rules:
- apiGroups:
  - wavefront.com
  resources:
  - wavefronts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wavefront.com
  resources:
  - wavefronts/status
  verbs:
  - get
