apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name : wavefront-proxy
    app.kubernetes.io/component: proxy
  name: wavefront-proxy
  namespace: wavefront
spec:
  ports:
    - name: wavefront
      port: 2878
      protocol: TCP
  selector:
    app.kubernetes.io/name : wavefront-proxy
    app.kubernetes.io/component: proxy
  type: ClusterIP