apiVersion: apps/v1
kind: Deployment
metadata:
  name: wavefront-operator
  namespace: wavefront
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wavefront-operator
  template:
    metadata:
      labels:
        name: wavefront-operator
    spec:
      serviceAccountName: wavefront-operator
      containers:
        - name: wavefront-operator
          image: wavefronthq/wavefront-operator-for-kubernetes:0.9.0
          command:
          - wavefront-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "wavefront-operator"
