apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront-sample
spec:
  clusterName: "shaoh-operator"
  wavefrontToken: "0602ce24-9e70-41dd-9b32-711ca33cc73c"
  wavefrontUrl: "https://nimba.wavefront.com"
