---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: taylorsilva/carvel-ytt
  version:
    tag: 0.36

inputs:
- name: ci_repo
params:
run:
  path: ci_repo/hack/concourse/tasks/generate-pipeline.sh
