---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/source_insight_tooling/osspi-runner

inputs:
- name: ci_repo
- name: feature_branches
params:
run:
  path: ci_repo/hack/concourse/tasks/generate-pipeline.sh
