apiVersion: v1
kind: ConfigMap
metadata:
  name: wavefront-logging-config-fluent-bit
  namespace: {{ .Namespace }}
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: wavefront-controller-manager
      uid: {{ .ControllerManagerUID }}
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: logging
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [OUTPUT]
        Name http
        Match kube.*
        Proxy http://wavefront-proxy:2878
        URI /logs/json_array?f=logs_json_lines
        Format json_lines
        json_date_key timestamp
        json_date_format epoch
    
    [OUTPUT]
        Name file
        Match *
        Path /tmp
    
    [FILTER]
        Name             kubernetes
        Match            kube.*
        Kube_URL         https://kubernetes.default.svc:443
        Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix  kube.var.log.containers.
        Merge_Log        On
        Merge_Log_Key    log_processed
        Labels           Off
        Annotations      Off
    
    [FILTER]
        Name  record_modifier
        Match kube.*
        Record source kind-control-plane
        Record cluster cornmichael-kind-1130-fluent-bit
