kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wavefront-logging
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - deployments
      - events
    verbs:
      - list
      - get
      - watch