apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: logging
  name: wavefront-logging
  namespace: {{ .Namespace }}
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: wavefront-controller-manager
      uid: {{ .ControllerManagerUID }}
automountServiceAccountToken: false