apiVersion: apps/v1
kind: Deployment
metadata:
  name: wavefront-proxy
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: proxy
  namespace: {{ .Namespace }}
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: wavefront-controller-manager
      uid: {{ .ControllerManagerUID }}
spec:
  replicas: {{ .DataExport.WavefrontProxy.Replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name : wavefront
      app.kubernetes.io/component: proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name : wavefront
        app.kubernetes.io/component: proxy
      annotations:
        configHash: "{{ .DataExport.WavefrontProxy.ConfigHash }}"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      containers:
        - name: wavefront-proxy
          image: {{ .ImageRegistry }}/proxy:12.0
          imagePullPolicy: Always
          env:
            - name: WAVEFRONT_URL
              value: {{ .WavefrontUrl }}/api/
            - name: WAVEFRONT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .WavefrontTokenSecret }}
                  key: token
            - name: WAVEFRONT_PROXY_ARGS
              value: >
                --pushListenerPorts {{ .DataExport.WavefrontProxy.MetricPort }}
                --buffer /wavefront-proxy/buffer
              {{- if .DataExport.WavefrontProxy.Args }} {{ .DataExport.WavefrontProxy.Args }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.DeltaCounterPort }} --deltaCounterPorts {{ .DataExport.WavefrontProxy.DeltaCounterPort }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Tracing.Wavefront.Port }} --traceListenerPorts {{ .DataExport.WavefrontProxy.Tracing.Wavefront.Port }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Tracing.Wavefront.SamplingRate }} --traceSamplingRate {{ .DataExport.WavefrontProxy.Tracing.Wavefront.SamplingRate }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Tracing.Wavefront.SamplingDuration }} --traceSamplingDuration {{ .DataExport.WavefrontProxy.Tracing.Wavefront.SamplingDuration }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Tracing.Jaeger.Port }} --traceJaegerListenerPorts {{ .DataExport.WavefrontProxy.Tracing.Jaeger.Port }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Tracing.Jaeger.GrpcPort }} --traceJaegerGrpcListenerPorts {{ .DataExport.WavefrontProxy.Tracing.Jaeger.GrpcPort }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Tracing.Jaeger.HttpPort }} --traceJaegerHttpListenerPorts {{ .DataExport.WavefrontProxy.Tracing.Jaeger.HttpPort }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Tracing.Jaeger.ApplicationName }} --traceJaegerApplicationName {{ .DataExport.WavefrontProxy.Tracing.Jaeger.ApplicationName }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Tracing.Zipkin.Port }} --traceZipkinListenerPorts {{ .DataExport.WavefrontProxy.Tracing.Zipkin.Port }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Tracing.Zipkin.ApplicationName }} --traceZipkinApplicationName {{ .DataExport.WavefrontProxy.Tracing.Zipkin.ApplicationName }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Histogram.Port }} --histogramDistListenerPorts {{ .DataExport.WavefrontProxy.Histogram.Port }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Histogram.MinutePort }} --histogramMinuteListenerPorts {{ .DataExport.WavefrontProxy.Histogram.MinutePort }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Histogram.HourPort }} --histogramHourListenerPorts {{ .DataExport.WavefrontProxy.Histogram.HourPort }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.Histogram.DayPort }} --histogramDayListenerPorts {{ .DataExport.WavefrontProxy.Histogram.DayPort }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.OLTP.GrpcPort}} --otlpGrpcListenerPorts {{ .DataExport.WavefrontProxy.OLTP.GrpcPort }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.OLTP.HttpPort}} --otlpHttpListenerPorts {{ .DataExport.WavefrontProxy.OLTP.HttpPort }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.OLTP.ResourceAttrsOnMetricsIncluded}} --otlpResourceAttrsOnMetricsIncluded true {{- end -}}
              {{- if .DataExport.WavefrontProxy.Preprocessor }} --preprocessorConfigFile /etc/wavefront/preprocessor/rules.yaml {{- end -}}
              {{- if .DataExport.WavefrontProxy.HttpProxy.HttpProxyHost }} --proxyHost {{ .DataExport.WavefrontProxy.HttpProxy.HttpProxyHost }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.HttpProxy.HttpProxyPort }} --proxyPort {{ .DataExport.WavefrontProxy.HttpProxy.HttpProxyPort }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.HttpProxy.HttpProxyUser }} --proxyUser {{ .DataExport.WavefrontProxy.HttpProxy.HttpProxyUser }} {{- end -}}
              {{- if .DataExport.WavefrontProxy.HttpProxy.HttpProxyPassword }} --proxyPassword {{ .DataExport.WavefrontProxy.HttpProxy.HttpProxyPassword }} {{- end -}}
              {{- if .DataCollection.Logging.Enable }} --customMessageTags log {{- end }}

          ports:
            - containerPort: {{ .DataExport.WavefrontProxy.MetricPort }}
              protocol: TCP
            {{- if .DataExport.WavefrontProxy.DeltaCounterPort}}
            - containerPort: {{ .DataExport.WavefrontProxy.DeltaCounterPort }}
              protocol: TCP
            {{- end }}
            {{- if .DataExport.WavefrontProxy.Tracing.Wavefront.Port}}
            - containerPort: {{ .DataExport.WavefrontProxy.Tracing.Wavefront.Port }}
              protocol: TCP
            {{- end }}
            {{- if .DataExport.WavefrontProxy.Tracing.Jaeger.Port}}
            - containerPort: {{ .DataExport.WavefrontProxy.Tracing.Jaeger.Port }}
              protocol: TCP
            {{- end }}
            {{- if .DataExport.WavefrontProxy.Tracing.Jaeger.GrpcPort}}
            - containerPort: {{ .DataExport.WavefrontProxy.Tracing.Jaeger.GrpcPort }}
              protocol: TCP
            {{- end }}
            {{- if .DataExport.WavefrontProxy.Tracing.Jaeger.HttpPort}}
            - containerPort: {{ .DataExport.WavefrontProxy.Tracing.Jaeger.HttpPort }}
              protocol: TCP
            {{- end }}
            {{- if .DataExport.WavefrontProxy.Tracing.Zipkin.Port}}
            - containerPort: {{ .DataExport.WavefrontProxy.Tracing.Zipkin.Port }}
              protocol: TCP
            {{- end }}
            {{- if .DataExport.WavefrontProxy.Histogram.Port}}
            - containerPort: {{ .DataExport.WavefrontProxy.Histogram.Port }}
              protocol: TCP
            {{- end }}
            {{- if .DataExport.WavefrontProxy.Histogram.MinutePort}}
            - containerPort: {{ .DataExport.WavefrontProxy.Histogram.MinutePort }}
              protocol: TCP
            {{- end }}
            {{- if .DataExport.WavefrontProxy.Histogram.HourPort}}
            - containerPort: {{ .DataExport.WavefrontProxy.Histogram.HourPort }}
              protocol: TCP
            {{- end }}
            {{- if .DataExport.WavefrontProxy.Histogram.DayPort}}
            - containerPort: {{ .DataExport.WavefrontProxy.Histogram.DayPort }}
              protocol: TCP
            {{- end }}
            {{- if .DataExport.WavefrontProxy.OLTP.GrpcPort}}
            - containerPort: {{ .DataExport.WavefrontProxy.OLTP.GrpcPort }}
              protocol: TCP
            {{- end }}
            {{- if .DataExport.WavefrontProxy.OLTP.HttpPort}}
            - containerPort: {{ .DataExport.WavefrontProxy.OLTP.HttpPort }}
              protocol: TCP
            {{- end }}
          readinessProbe:
            timeoutSeconds: 10
            failureThreshold: 10
            tcpSocket:
              port: {{ .DataExport.WavefrontProxy.MetricPort }}
          resources:
{{ .DataExport.WavefrontProxy.Resources | toYaml | indent 12 }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
          - name: buffer-volume
            mountPath: /wavefront-proxy
          {{- if .DataExport.WavefrontProxy.Preprocessor}}
          - name: preprocessor
            mountPath: /etc/wavefront/preprocessor
          {{- end }}
          {{- if .DataExport.WavefrontProxy.HttpProxy.UseHttpProxyCAcert}}
          - name: http-proxy-ca
            mountPath: /tmp/ca
          {{- end }}
      volumes:
      - name: buffer-volume
        emptyDir: {}
      {{- if .DataExport.WavefrontProxy.Preprocessor }}
      - name: preprocessor
        configMap:
          name: {{ .DataExport.WavefrontProxy.Preprocessor }}
      {{- end }}
      {{- if .DataExport.WavefrontProxy.HttpProxy.UseHttpProxyCAcert }}
      - name: http-proxy-ca
        secret:
          secretName: {{ .DataExport.WavefrontProxy.HttpProxy.Secret }}
          items:
            - key: tls-root-ca-bundle
              path: ca.pem
      {{- end }}

