# Need to change YOUR_CLUSTER_NAME and YOUR_WAVEFRONT_URL accordingly
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: observability-system
spec:
  clusterName: YOUR_CLUSTER_NAME
  wavefrontUrl: YOUR_WAVEFRONT_URL
  dataCollection:
    metrics:
      enable: true
      clusterCollector:
        resources:
          requests:
            cpu: 200m
            memory: 10Mi
          limits:
            cpu: 400m
            memory: 512Mi
      nodeCollector:
        resources:
          requests:
            cpu: 200m
            memory: 10Mi
          limits:
            cpu: 200m
            memory: 256Mi
  dataExport:
    wavefrontProxy:
      enable: true
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 3Gi
