# Need to change YOUR_CLUSTER_NAME and YOUR_WAVEFRONT_URL accordingly
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: observability-system
spec:
  clusterName: YOUR_CLUSTER_NAME
  wavefrontUrl: YOUR_WAVEFRONT_URL
  dataCollection:
    metrics:
      enable: true
  dataExport:
    wavefrontProxy:
      enable: true
      # Note on Configuration Precedence
      #
      # Most wavefront proxy configuration options should be available via explicit fields in the custom resource.
      # It is our recommendation to use those fields. However, it is also possible to specify options as proxy command
      # line parameters in the `dataExport.wavefrontProxy.args` field. If both are used, the operator will allow it at
      # this time, but the custom resource field will take precedence.
      #
      # For example, if you specify `--histogramDistListenerPorts 40123` in `dataExport.wavefrontProxy.args`
      #  and `dataExport.wavefrontProxy.histogram.port: 40000`,
      #  `dataExport.wavefrontProxy.histogram.port: 40000` will take precedence.
      args: >
        --customSourceTags mySource
        --prefix=dev

