# Need to change YOUR_CLUSTER_NAME and YOUR_WAVEFRONT_URL accordingly
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: wavefront
spec:
  clusterName: YOUR_CLUSTER_NAME
  wavefrontUrl: YOUR_WAVEFRONT_URL
  wavefrontTokenSecret: wavefront-secret
  dataCollection:
    metrics:
      enable: true
  dataExport:
    wavefrontProxy:
      enable: true
      preprocessor: advanced-proxy-preprocessor-rules
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: advanced-proxy-preprocessor-rules
  namespace: wavefront
data:
  rules.yaml: |
    '2878':
      - rule: tag-all-metrics-processed
        action: addTag
        tag: processed
        value: "true"
