# Need to change YOUR_CLUSTER_NAME and YOUR_WAVEFRONT_URL accordingly
# See https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/main/docs/discovery.md#plugin-types for more details
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: observability-system
spec:
  clusterName: YOUR_CLUSTER_NAME
  wavefrontUrl: YOUR_WAVEFRONT_URL
  dataExport:
    wavefrontProxy:
      enable: true
  dataCollection:
    metrics:
      enable: true
---
apiVersion: v1
kind: Secret
metadata:
  name: plugin-example-config
  namespace: observability-system
  annotations:
    wavefront.com/discovery-config: 'true'
stringData:
  collector.yaml: |
    # specify a list of discovery rules (plugins)
    plugins:
    
    # memcached
    - name: memcached
      type: telegraf/memcached
      selectors:
        images:
        - 'memcached:*'
      port: 11211
      conf: |
        servers = ["${host}:${port}"]
    
    # mysql
    - name: mysql
      type: telegraf/mysql
      selectors:
        images:
        - "mysql*"
      collection:
        interval: "180s"
      port: 3306
      conf: |
        servers = ["root:password@tcp(${host}:${port})/?tls=false"]
        perf_events_statements_digest_text_limit  = 120
        perf_events_statements_limit              = 250
        perf_events_statements_time_limit         = 86400
        table_schema_databases                    = []
        gather_process_list                       = true
        gather_table_io_waits                     = true
        gather_table_lock_waits                   = true
        gather_index_io_waits                     = true
        gather_event_waits                        = true
        gather_file_events_stats                  = true
        interval_slow                             = "30m"