apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- wavefront-operator.yaml

images:
- name: projects.registry.vmware.com/tanzu_observability/kubernetes-operator
  newName: YOUR_IMAGE_REGISTRY/kubernetes-operator
