apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name : wavefront
    app.kubernetes.io/component: proxy
  name: wavefront-proxy
  namespace: wavefront
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: wavefront-controller-manager
      uid: {{ .ControllerManagerUID }}
spec:
  ports:
    - name: wavefront
      port: {{ .DataExport.Proxy.MetricPort }}
      protocol: TCP
    {{if .DataExport.Proxy.DeltaCounterPort}}
    - name: delta-counter
      port: {{ .DataExport.Proxy.DeltaCounterPort }}
      protocol: TCP
    {{end}}
    {{if .DataExport.Proxy.Tracing.Wavefront.Port}}
    - name: wavefront-trace
      port: {{ .DataExport.Proxy.Tracing.Wavefront.Port }}
      protocol: TCP
    {{end}}
    {{if .DataExport.Proxy.Tracing.Jaeger.Port}}
    - name: jaeger
      port: {{ .DataExport.Proxy.Tracing.Jaeger.Port }}
      protocol: TCP
    {{end}}
    {{if .DataExport.Proxy.Tracing.Jaeger.GrpcPort}}
    - name: jaeger-grpc
      port: {{ .DataExport.Proxy.Tracing.Jaeger.GrpcPort }}
      protocol: TCP
    {{end}}
    {{if .DataExport.Proxy.Tracing.Jaeger.HttpPort}}
    - name: jaeger-http
      port: {{ .DataExport.Proxy.Tracing.Jaeger.HttpPort }}
      protocol: TCP
    {{end}}
    {{if .DataExport.Proxy.Tracing.Zipkin.Port}}
    - name: zipkin
      port: {{ .DataExport.Proxy.Tracing.Zipkin.Port }}
      protocol: TCP
    {{end}}
  selector:
    app.kubernetes.io/name : wavefront
    app.kubernetes.io/component: proxy
  type: ClusterIP