apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name : wavefront
    app.kubernetes.io/component: proxy
  name: wavefront-proxy
  namespace: wavefront
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: wavefront-controller-manager
      uid: {{ .ControllerManagerUID }}
spec:
  ports:
    - name: wavefront
      port: {{ .DataExport.Proxy.MetricPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name : wavefront
    app.kubernetes.io/component: proxy
  type: ClusterIP