apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: proxy
  name: wavefront-proxy
  namespace: wavefront
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: wavefront-controller-manager
      uid: {{ .ControllerManagerUID }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name : wavefront
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name : wavefront
        app.kubernetes.io/component: proxy
    spec:
      containers:
        - name: wavefront-proxy
          image: projects.registry.vmware.com/tanzu_observability/proxy:11.0
          imagePullPolicy: IfNotPresent
          env:
            - name: WAVEFRONT_URL
              value: {{.WavefrontUrl}}/api/
            - name: WAVEFRONT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{.WavefrontTokenSecret}}
                  key: token
            - name: WAVEFRONT_PROXY_ARGS
              value: --pushListenerPorts {{ .DataExport.Proxy.MetricPort }}
              {{- if .DataExport.Proxy.HttpProxy.Host }} --proxyHost {{ .DataExport.Proxy.HttpProxy.Host }} {{- end -}}
              {{- if .DataExport.Proxy.HttpProxy.Port }} --proxyPort {{ .DataExport.Proxy.HttpProxy.Port }} {{- end -}}
              {{- if .DataExport.Proxy.HttpProxy.User }} --proxyUser {{ .DataExport.Proxy.HttpProxy.User }} {{- end -}}
              {{- if .DataExport.Proxy.HttpProxy.Password }} --proxyPassword {{ .DataExport.Proxy.HttpProxy.Password }} {{- end -}}
              {{- if .DataExport.Proxy.DeltaCounterPort }} --deltaCounterPorts {{ .DataExport.Proxy.DeltaCounterPort }} {{- end -}}
              {{- if .DataExport.Proxy.Tracing.Wavefront.Port }} --traceListenerPorts {{ .DataExport.Proxy.Tracing.Wavefront.Port }} {{- end -}}
              {{- if .DataExport.Proxy.Tracing.Wavefront.SamplingRate }} --traceSamplingRate {{ .DataExport.Proxy.Tracing.Wavefront.SamplingRate }} {{- end -}}
              {{- if .DataExport.Proxy.Tracing.Wavefront.SamplingDuration }} --traceSamplingDuration {{ .DataExport.Proxy.Tracing.Wavefront.SamplingDuration }} {{- end }}
          ports:
            - containerPort: {{ .DataExport.Proxy.MetricPort }}
              protocol: TCP
            {{- if .DataExport.Proxy.DeltaCounterPort}}
            - containerPort: {{ .DataExport.Proxy.DeltaCounterPort }}
              protocol: TCP
            {{- end }}
            {{- if .DataExport.Proxy.Tracing.Wavefront.Port}}
            - containerPort: {{ .DataExport.Proxy.Tracing.Wavefront.Port }}
              protocol: TCP
            {{- end }}
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 1Gi
          securityContext:
            privileged: false
