apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: proxy
  name: wavefront-proxy
  namespace: wavefront
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: wavefront-controller-manager
      uid: {{ .ControllerManagerUID }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name : wavefront
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name : wavefront
        app.kubernetes.io/component: proxy
    spec:
      containers:
        - name: wavefront-proxy
          image: projects.registry.vmware.com/tanzu_observability/proxy:11.0
          imagePullPolicy: IfNotPresent
          env:
            - name: WAVEFRONT_URL
              value: {{.WavefrontUrl}}/api/
            - name: WAVEFRONT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{.WavefrontTokenSecret}}
                  key: token
          ports:
            - containerPort: {{ .DataExport.Proxy.Port }}
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 1Gi
          securityContext:
            privileged: false
