---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manual-install-detection
  namespace: wavefront-collector
rules:
- apiGroups:
  - ""
  resources:
  - daemonsets
  - deployments
  verbs:
  - get
  - list