apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manual-install-detection-rolebinding
  namespace: wavefront
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manual-install-detection-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: wavefront
